logging:
  level:
    root: info
spring:
  cloud:
    config:
      server:
        native:
          search-locations: file:${user.dir}/config-repo
  config:
    activate:
      on-profile: native

management:
  endpoint:
    health:
      show-details: "ALWAYS"
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8888
---
spring:
  cloud:
    config:
      server:
        native:
          search-locations: file:/config-repo
  config:
    activate:
      on-profile: docker
